/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package conversorbase;

/**
 *
 * @author Renan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        origem = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        destino = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        saida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Bases v.0.1");
        setResizable(false);
        setSize(new java.awt.Dimension(438, 220));

        jLabel1.setText("Número a ser convertido");

        numero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                validarNumero(evt);
            }
        });

        jLabel2.setText("Base de origem");

        origem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "16" }));
        origem.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                limparNumero(evt);
            }
        });

        jLabel3.setText("Base de destino");

        destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10", "16" }));

        jButton1.setText("CONVERTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        saida.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numero)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(origem, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(saida))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(origem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        int base10 = 0;
        int baseDestino, baseOrigem;
        String resultado = "";
        
        baseOrigem = Integer.parseInt(origem.getSelectedItem().toString());
        
        //Converter incialmente para a base 10
        if(baseOrigem == 10) {
            base10 = Integer.parseInt(numero.getText());
        }
        else{
            String num = numero.getText();
            int valor;
            base10 = 0;
            for(int i=0; i<num.length(); i++) {
                switch(num.charAt(i)) {
                    case 'A': valor = 10; break;
                    case 'B': valor = 11; break;
                    case 'C': valor = 12; break;
                    case 'D': valor = 13; break;
                    case 'E': valor = 14; break;
                    case 'F': valor = 15; break;
                    default: valor = Integer.parseInt("" + num.charAt(i)); break;
                } 
                base10 += valor*Math.pow(baseOrigem, num.length()-i-1);
            }
        }
        
        baseDestino = Integer.parseInt(destino.getSelectedItem().toString());
        
        //Convertendo para a base de destino
        if(baseDestino == 10) {
            saida.setText(String.valueOf(base10));
        }
        else {
            while (base10/baseDestino != 0){
                switch(base10%baseDestino) {
                    case 10: resultado += "A"; break;
                    case 11: resultado += "B"; break;
                    case 12: resultado += "C"; break;
                    case 13: resultado += "D"; break;
                    case 14: resultado += "E"; break;
                    case 15: resultado += "F"; break;
                    default: resultado += base10%baseDestino; break;
                }
                base10 /= baseDestino; 
            }
            
            switch(base10%baseDestino) {
                    case 10: resultado += "A"; break;
                    case 11: resultado += "B"; break;
                    case 12: resultado += "C"; break;
                    case 13: resultado += "D"; break;
                    case 14: resultado += "E"; break;
                    case 15: resultado += "F"; break;
                    default: resultado += base10%baseDestino; break;
                }
            
            StringBuilder sb = new StringBuilder(resultado);
            sb.reverse();
            resultado = sb.toString();
            saida.setText(resultado);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void validarNumero(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_validarNumero
        String texto = numero.getText().toUpperCase();
        
        int pos = texto.length()-1;
        char c = texto.charAt(pos);
        int n;
        
        int baseOrigem= Integer.parseInt(origem.getSelectedItem().toString());
        
        try {   
            n = Integer.parseInt("" + c);
        }
        catch(NumberFormatException e) {
            n = baseOrigem;
        }
        
        if (baseOrigem == 16) {
            if (c != 'A' && c != 'B' && c != 'C' && c != 'D' && c != 'E' && c != 'F' && n == baseOrigem)
                texto = texto.substring(0, pos);
        } else {
            if(n >= baseOrigem)
                texto = texto.substring(0, pos);
        }

        numero.setText(texto);
    }//GEN-LAST:event_validarNumero

    private void limparNumero(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_limparNumero
        numero.setText("");
    }//GEN-LAST:event_limparNumero

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox destino;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numero;
    private javax.swing.JComboBox origem;
    private javax.swing.JTextField saida;
    // End of variables declaration//GEN-END:variables
}
